# Generated by Django 4.0.6 on 2023-04-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=120)),
                ('certification_completion_id', models.IntegerField()),
                ('certification_url', models.CharField(max_length=100)),
                ('certification_validity', models.DateField()),
                ('certification_will_expire', models.BooleanField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('univesity', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('speclalization', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=50)),
                ('course_duration', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True)),
                ('grading_system', models.CharField(max_length=100)),
                ('marks', models.IntegerField(blank=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_industry', models.CharField(max_length=120)),
                ('preferred_shift', models.CharField(max_length=50)),
                ('preferred_work_location', models.CharField(max_length=122)),
                ('expected_salary', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('differently_abled', models.BooleanField()),
                ('career_break', models.BooleanField()),
                ('reasonforbreak', models.CharField(max_length=150)),
                ('work_permit_for_any_countries', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('tag_this_project_with_your_Education', models.BooleanField()),
                ('client_name', models.CharField(max_length=20)),
                ('project_staus', models.BooleanField()),
                ('workd_from', models.DateField()),
                ('project_details', models.CharField(max_length=300)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('software_version', models.IntegerField()),
                ('last_used', models.DateField()),
                ('experience', models.DateField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_socialprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_profile', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('duration_from', models.DateField()),
                ('duration_to', models.BooleanField()),
                ('working_staus', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience_detail',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='seeker_profile',
            name='user_account_id',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='password',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='email',
            new_name='experience_level',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='user_image',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='email_notification_active',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='user_account',
            name='join_type',
            field=models.CharField(default='', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_account',
            name='resume',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='education_detail',
        ),
        migrations.DeleteModel(
            name='experience_detail',
        ),
        migrations.DeleteModel(
            name='seeker_profile',
        ),
        migrations.AddField(
            model_name='user_workstatus',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_workstatus', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_socialprofile',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_socialprofile', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_skills',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_skills', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_projects',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_projects', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_personalinfo',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_personalinfo', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_education',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_education', to='recruitement.user_account'),
        ),
        migrations.AddField(
            model_name='user_certification',
            name='user_account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_user_certification', to='recruitement.user_account'),
        ),
        migrations.AlterField(
            model_name='job_post_skill_set',
            name='skill_set_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_id', to='recruitement.user_skills'),
        ),
        migrations.AlterField(
            model_name='seeker_skill_set',
            name='skill_set_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_id_seeker', to='recruitement.user_skills'),
        ),
        migrations.DeleteModel(
            name='skill_set',
        ),
    ]
