# Generated by Django 4.0.6 on 2023-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0002_user_certification_user_education_user_personalinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
