# Generated by Django 4.0.6 on 2023-04-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0003_alter_user_account_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(max_length=50)),
                ('is_current_employment', models.BooleanField()),
                ('total_experince', models.DateField()),
                ('current_company_name', models.CharField(max_length=20)),
                ('current_designation', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('current_salary', models.IntegerField()),
                ('skills_used', models.CharField(max_length=200)),
                ('job_profile', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('user_account_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_account_id_employment', to='recruitement.user_account')),
            ],
        ),
    ]
