# Generated by Django 4.0.6 on 2023-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0004_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workstatus',
            name='duration_to',
            field=models.DateField(),
        ),
    ]
