# Generated by Django 4.0.6 on 2023-04-10 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0005_alter_user_workstatus_duration_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_certification',
            old_name='certification_validity',
            new_name='certification_validity_from',
        ),
        migrations.AddField(
            model_name='user_certification',
            name='certification_validity_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
