# Generated by Django 4.0.6 on 2023-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0008_alter_user_personalinfo_reasonforbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
