# Generated by Django 4.0.6 on 2023-04-11 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0009_user_account_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_skills',
            old_name='experience',
            new_name='experience_month',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='experience_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
