# Generated by Django 4.0.6 on 2023-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitement', '0010_rename_experience_user_skills_experience_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_workstatus',
            old_name='duration_from',
            new_name='duration_from_month',
        ),
        migrations.RenameField(
            model_name='user_workstatus',
            old_name='duration_to',
            new_name='duration_from_year',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='total_experince',
        ),
        migrations.RemoveField(
            model_name='user_projects',
            name='workd_from',
        ),
        migrations.AddField(
            model_name='employment',
            name='joining_date_month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='joining_date_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='total_experince_month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='total_experince_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_projects',
            name='worked_from_month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_projects',
            name='worked_from_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_workstatus',
            name='duration_to_month',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_workstatus',
            name='duration_to_year',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_certification',
            name='certification_validity_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_certification',
            name='certification_validity_to',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_education',
            name='completion_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_education',
            name='course_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_skills',
            name='experience_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_skills',
            name='experience_year',
            field=models.IntegerField(),
        ),
    ]
